### ISSUE TITLE
How to install this alongside retrofit 2.1.0?

### ISSUE THREAD

**Issue by aaronbond** [JakeWharton/okhttp-idling-resource#8]
i seem to have an issue with different versions of okhttp between my build and my test:

> Warning:Conflict with dependency 'com.squareup.okhttp3:okhttp'. Resolved versions for app (3.3.1) and test app (3.4.0) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.squareup.okio:okio'. Resolved versions for app (1.8.0) and test app (1.9.0) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

and when i force it to use either version 3.3.1 or 3.4.0 i will get an issue either in running my tests or during my build for example when i force it to use the older version:

>java.lang.NoSuchMethodError: No virtual method setIdleCallback(Ljava/lang/Runnable;)V in class Lokhttp3/Dispatcher; or its super classes (declaration of 'okhttp3.Dispatcher' appears in /data/app/com.unlockd.mobile.testapp-1/base.apk)
at com.jakewharton.espresso.OkHttp3IdlingResource.<init>(OkHttp3IdlingResource.java:45)
at com.jakewharton.espresso.OkHttp3IdlingResource.create(OkHttp3IdlingResource.java:35)

will appear in my tests and when i force the newer version my tests work fine with the idling resource but during the running of my app:

>E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                  Process: com.unlockd.mobile.testapp, PID: 4590
                  java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/internal/http/HttpEngine;
                      at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:232)
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                      at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
                      at okhttp3.RealCall.access$100(RealCall.java:33)
                      at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
                      at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                      at java.lang.Thread.run(Thread.java:818)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.internal.http.HttpEngine" on path: DexPathList[[zip file "/data/app/com.unlockd.mobile.testapp-2/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                      at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:232) 
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                      at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170) 
                      at okhttp3.RealCall.access$100(RealCall.java:33) 
                      at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120) 
                      at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                      at java.lang.Thread.run(Thread.java:818) 
                  	Suppressed: java.lang.ClassNotFoundException: okhttp3.internal.http.HttpEngine
                      at java.lang.Class.classForName(Native Method)
                      at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                      at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                      		... 11 more
                   Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

any ideas on what i'm doing wrong? how do you get okhttp-idling-resource and retrofit to work side by side?

**Comment by inetaa** [comment]
Hi! I have the same issue. How did you solve this?

**Comment by jweaver** [comment]
I'd like to know as well.
